name: metocean-ml
channels:
  - conda-forge
dependencies:
  - python=>3.9
  - xarray
  - matplotlib>=3.1
  - numpy>=1.17
  - pandas>=2.2.1
  - pip
  - scipy
  - pytest
  - scikit-learn
  - keras
  - tensorflow

